### ISSUE TITLE
用不了，能教下吗，go run报错

### ISSUE THREAD

**Issue by menxiaoguo** [NullpointerW/rbnb-pow-mint#1]
用不了，能教下吗，go run报错

**Comment by NullpointerW** [comment]
提供下错误信息

**Comment by menxiaoguo** [comment]
运行
go run genw.go
报错
# command-line-arguments
runtime.main_main·f: function main is undeclared in the main package
运行
go run main.go
报错
# command-line-arguments
.\main.go:97:14: undefined: genWallet


谢谢大佬

**Comment by NullpointerW** [comment]
在项目路径下运行 go build 编译成exe 运行即可

**Comment by menxiaoguo** [comment]
嗯嗯  谢谢
